import { notFound } from "next/navigation";
import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { format } from "date-fns";
import { ReportPhotosLightbox } from "./report-photos-lightbox";

export default async function ReportPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const job = await prisma.job.findUnique({
    where: { reportSlug: slug },
    include: { photos: { orderBy: { createdAt: "asc" } }, signature: true },
  });
  if (!job) notFound();

  return (
    <div className="min-h-screen bg-stone-100 pb-[env(safe-area-inset-bottom)]">
      <div className="mx-auto max-w-2xl bg-white px-4 py-6 shadow-sm sm:px-6 sm:py-8">
        <header className="border-b border-stone-200 pb-6">
          <h1 className="text-xl font-bold text-stone-900">Proof of work report</h1>
          <p className="mt-1 text-sm text-stone-500">
            Generated with{" "}
            <Link href="/" className="font-medium text-primary hover:underline">
              Site Agent
            </Link>
          </p>
        </header>

        <dl className="mt-6 grid gap-2 border-b border-stone-200 pb-6">
          <dt className="text-stone-500">Job</dt>
          <dd className="font-medium text-stone-900">{job.title}</dd>
          {job.clientName && (
            <>
              <dt className="text-stone-500">Client</dt>
              <dd className="text-stone-700">{job.clientName}</dd>
            </>
          )}
          {job.address && (
            <>
              <dt className="text-stone-500">Address</dt>
              <dd className="text-stone-700">{job.address}</dd>
            </>
          )}
          <dt className="text-stone-500">Date</dt>
          <dd className="text-stone-700">{format(job.updatedAt, "d MMMM yyyy, HH:mm")}</dd>
        </dl>

        {job.notes && (
          <section className="border-b border-stone-200 py-6">
            <h2 className="text-sm font-semibold uppercase tracking-wide text-stone-500">Notes</h2>
            <p className="mt-2 whitespace-pre-wrap text-stone-700">{job.notes}</p>
          </section>
        )}

        {job.photos.length > 0 && (
          <ReportPhotosLightbox
            photos={job.photos.map((p) => ({
              id: p.id,
              imageUrl: p.imageUrl,
              note: p.note,
              tag: p.tag,
              createdAt: p.createdAt,
              latitude: p.latitude,
              longitude: p.longitude,
            }))}
          />
        )}

        {job.signature && (
          <section className="py-6">
            <h2 className="text-sm font-semibold uppercase tracking-wide text-stone-500">
              Contractor signature
            </h2>
            <div className="mt-2 flex items-center gap-4">
              <img
                src={job.signature.signatureImageUrl}
                alt="Signature"
                className="max-h-20 w-auto border-b-2 border-stone-400"
              />
              {job.signature.signedBy && (
                <span className="text-stone-600">— {job.signature.signedBy}</span>
              )}
            </div>
          </section>
        )}

        {job.clientSignedAt && job.clientSignatureUrl && (
          <section className="py-6">
            <h2 className="text-sm font-semibold uppercase tracking-wide text-stone-500">
              Client sign-off
            </h2>
            <p className="mt-1 text-xs text-stone-500">
              Signed on {format(new Date(job.clientSignedAt), "d MMMM yyyy, HH:mm")}
            </p>
            <div className="mt-2 flex items-center gap-4">
              <img
                src={job.clientSignatureUrl}
                alt="Client signature"
                className="max-h-20 w-auto border-b-2 border-stone-400"
              />
              {job.clientSignedBy && (
                <span className="text-stone-600">— {job.clientSignedBy}</span>
              )}
            </div>
          </section>
        )}

        <footer className="mt-8 border-t border-stone-200 pt-6 text-center text-sm text-stone-500">
          This report was generated by Site Agent. Proof your work. Prevent disputes. Get paid.
        </footer>
      </div>
    </div>
  );
}
