import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { format } from "date-fns";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
  renderToBuffer,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 10 },
  title: { fontSize: 16, marginBottom: 8, fontWeight: "bold" },
  subtitle: { fontSize: 9, color: "#666", marginBottom: 20 },
  section: { marginBottom: 16 },
  label: { fontSize: 8, color: "#666", marginBottom: 2 },
  value: { fontSize: 10 },
  photoBlock: { marginBottom: 12 },
  photo: { width: "100%", maxHeight: 200, objectFit: "contain" },
  photoCaption: { fontSize: 8, color: "#666", marginTop: 4 },
  signature: { marginTop: 8, marginBottom: 4 },
  sigImg: { height: 40, width: 200 },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, fontSize: 8, color: "#888" },
});

type JobForPdf = NonNullable<
  Awaited<ReturnType<typeof getJobForPdf>>
>;

async function getJobForPdf(slug: string) {
  return prisma.job.findUnique({
    where: { reportSlug: slug },
    include: { photos: true, signature: true },
  });
}

function ReportDocument({ job }: { job: JobForPdf }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Proof of work report</Text>
        <Text style={styles.subtitle}>Generated with SiteProof — {format(job.updatedAt, "d MMMM yyyy, HH:mm")}</Text>

        <View style={styles.section}>
          <Text style={styles.label}>Job</Text>
          <Text style={styles.value}>{job.title}</Text>
        </View>
        {job.clientName && (
          <View style={styles.section}>
            <Text style={styles.label}>Client</Text>
            <Text style={styles.value}>{job.clientName}</Text>
          </View>
        )}
        {job.address && (
          <View style={styles.section}>
            <Text style={styles.label}>Address</Text>
            <Text style={styles.value}>{job.address}</Text>
          </View>
        )}

        {job.notes && (
          <View style={styles.section}>
            <Text style={styles.label}>Notes</Text>
            <Text style={styles.value}>{job.notes}</Text>
          </View>
        )}

        {job.photos.length > 0 &&
          (["condition", "before", "after", null] as const).map((tag) => {
            const group = job.photos.filter((p) => (p.tag ?? null) === tag);
            if (group.length === 0) return null;
            const title =
              tag === "condition"
                ? "Condition on arrival (damage protection)"
                : tag === "before"
                  ? "Before"
                  : tag === "after"
                    ? "After"
                    : "Photos";
            return (
              <View key={tag ?? "other"} style={styles.section}>
                <Text style={styles.label}>{title}</Text>
                {group.map((p) => (
                  <View key={p.id} style={styles.photoBlock}>
                    {p.imageUrl.startsWith("data:") && (
                      <Image src={p.imageUrl} style={styles.photo} />
                    )}
                    <Text style={styles.photoCaption}>
                      {format(new Date(p.createdAt), "d MMM yyyy, HH:mm")}
                      {p.note ? ` — ${p.note}` : ""}
                      {p.latitude != null && p.longitude != null
                        ? ` — Location: ${p.latitude.toFixed(5)}, ${p.longitude.toFixed(5)}`
                        : ""}
                    </Text>
                  </View>
                ))}
              </View>
            );
          })}

        {job.signature && (
          <View style={styles.section}>
            <Text style={styles.label}>Signature</Text>
            <View style={styles.signature}>
              <Image src={job.signature.signatureImageUrl} style={styles.sigImg} />
              {job.signature.signedBy && (
                <Text style={styles.value}>— {job.signature.signedBy}</Text>
              )}
            </View>
          </View>
        )}

        <Text style={styles.footer}>
          This report was generated by SiteProof. Proof your work. Prevent disputes. Get paid.
        </Text>
      </Page>
    </Document>
  );
}

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params;
  const job = await getJobForPdf(slug);
  if (!job) {
    return NextResponse.json({ error: "Report not found" }, { status: 404 });
  }

  try {
    const buffer = await renderToBuffer(<ReportDocument job={job} />);
    const body = buffer instanceof Buffer ? buffer : Buffer.from(buffer);
    return new NextResponse(new Uint8Array(body), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="siteproof-report-${slug}.pdf"`,
      },
    });
  } catch (e) {
    console.error("PDF generation failed:", e);
    return NextResponse.json({ error: "Failed to generate PDF" }, { status: 500 });
  }
}
